# Project: Project2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = AlterMmain.o FilesIO.o Method.o U1.o Untitled-1.o
LINKOBJ  = AlterMmain.o FilesIO.o Method.o U1.o Untitled-1.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -mwindows -g3
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project2.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

AlterMmain.o: AlterMmain.cpp
	$(CPP) -c AlterMmain.cpp -o AlterMmain.o $(CXXFLAGS)

FilesIO.o: FilesIO.cpp
	$(CPP) -c FilesIO.cpp -o FilesIO.o $(CXXFLAGS)

Method.o: Method.cpp
	$(CPP) -c Method.cpp -o Method.o $(CXXFLAGS)

U1.o: U1.cpp
	$(CPP) -c U1.cpp -o U1.o $(CXXFLAGS)

Untitled-1.o: Untitled-1.cpp
	$(CPP) -c Untitled-1.cpp -o Untitled-1.o $(CXXFLAGS)
